### PR TITLE
Add characters say

### PR DESCRIPTION
**Pull request by Kiryuanzu**
Please check the issue!
https://github.com/htk291/p5-Acme-PriPara/issues/8

### CODE REVIEW

**Comment by htk291** [comment]
looks good 👍
wait a few days, sorry..

**Comment by htk291** [comment]
Sorry for not responding long time.
the code is okay, but setting files such as META.json and README.md are bit wrong (your name on its CI setting).

Would you correct it or I will merge and fix it, which do you want?

**Comment by AnaTofuZ** [comment]
@htk291 @Kiryuanzu 
I was put in the maintainer.
This will be fixed at the time of `$minil release`, so I think it's okay.

**Comment by htk291** [comment]
@AnaTofuZ 
thank you so much!!

**Comment by AnaTofuZ** [comment]
@htk291  I'm going to merge!! (@Kiryuanzu++ !)
download

**Pull request merged**
